apiVersion: v1
kind: Pod
metadata:
  name: python-web
  labels:
    app: python
spec:
  containers:
  - name: python
    image: python
    command: ["python", "-m", "http.server", "8080"]
    ports:
    - containerPort: 8080
