apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: devops
  source:
    helm:
      valueFiles:
      - ci/singapore-test-values.yaml
    path: kafka/kafka-3.3.1
    repoURL: git@github.com:junghoon2/k8s-class.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
