{{- if (include "mariadb-galera.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mariadb-root-password: {{ default (randAlphaNum 10) .Values.rootUser.password | b64enc | quote }}
  mariadb-password: {{ default (randAlphaNum 10) .Values.db.password | b64enc | quote }}
  mariadb-galera-mariabackup-password: {{ default (randAlphaNum 10) .Values.galera.mariabackup.password | b64enc | quote }}
  {{- if and .Values.ldap.enabled .Values.ldap.bindpw }}
  ldap-bindpw: {{ .Values.ldap.bindpw | b64enc | quote }}
  {{- end }}
{{- end }}
