apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-echo
  namespace: default
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo-pod
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do echo ERROR; sleep 10; done"
