# helm diff upgrade --values values.yaml loki grafana/loki --version 6.16.0 -n monitoring

serviceAccount:
  create: true
  name: loki
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::xxxx"

loki:
  auth_enabled: false

  compactor:
    working_directory: /var/loki
    compaction_interval: 10m

  ingester:
    chunk_encoding: snappy

  ingester_client:
    remote_timeout: 10s

  limits_config:
    per_tenant_override_config: /etc/overrides.yaml
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 24h
    per_stream_rate_limit: 30MB
    per_stream_rate_limit_burst: 50MB
    max_entries_limit_per_query: 20000
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 30
    max_query_parallelism: 32
    max_query_length: 0h
    max_query_series: 1000000
    max_entries_limit_per_query: 10000
    max_global_streams_per_user: 10000

  querier:
    max_concurrent: 8

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  server:
    grpc_server_max_concurrent_streams: 500
    grpc_server_max_recv_msg_size: 1.048576e+11
    grpc_server_max_send_msg_size: 1.048576e+11
    http_server_read_timeout: 30m
    http_server_write_timeout: 30m
    http_server_idle_timeout: 30m

  storage:
    type: "s3"
    s3:
      region: ap-northeast-2
    bucketNames:
      chunks: "loki-chunks"
      ruler: "loki-chunks"
      admin: "loki-chunks"

  tracing:
    enabled: true

deploymentMode: SimpleScalable

write:
  replicas: 3

  resources: 
    requests:
      cpu: 100m
      memory: 3Gi
    limits:
      memory: 3Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: write
          topologyKey: kubernetes.io/hostname

read:
  replicas: 3

  resources: 
    requests:
      cpu: 100m
      memory: 4Gi
    limits:
      memory: 4Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: read
          topologyKey: kubernetes.io/hostname

backend:
  replicas: 3

  resources: 
    requests:
      cpu: 50m
      memory: 1500Mi
    limits:
      memory: 1500Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: backend
          topologyKey: kubernetes.io/hostname

# Disable minio storage
minio:
  enabled: false

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
