rootUser:
  password: "MjId1vsl8E70"
galera:
  mariabackup:
    password: "xvK7VLd5Vm%"
persistence:
  size: 50Gi
  storageClass: "openebs-hostpath"
metrics:
  enabled: true
extraVolumes:
- name: mariadb-backup
  persistentVolumeClaim:
    claimName: mariadb-backup-pvc
extraVolumeMounts:
- name: mariadb-backup
  mountPath: /backup-vol
