catalog:
  serviceAccountName:
    enabled: true
    name: catalog-deployment-sa
  volume:
    enabled: true
    name: secrets-store-volumne
    path: "/mnt/secrets"
    csi:
      driver: secrets-store.csi.k8s.io
      volumeAttributes:
        secretProviderClass: catalog-deployment-spc-k8s-secrets

  image:
    tag: "10.0"
    
  env:
    - name: AGG_APP_URL
      value: "http://proddetail.workshop:3000/catalogDetail"
    - name: AWS_XRAY_DAEMON_ADDRESS
      value: xray-service.default:2000
    - name: DATABASE_SERVICE_URL
      value: mysql.workshop
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret-from-secrets-manager
          key: db_password
