{{- if and .Values.enabled .Values.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-tmp
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
{{- end }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end -}}
{{- end }}
  selector:
{{- if .Values.persistence.matchLabels }}
    matchLabels:
      {{- toYaml .Values.persistence.matchLabels | nindent 6 }}
{{- end -}}
{{- if .Values.persistence.matchExpressions }}
    matchExpressions:
      {{- toYaml .Values.persistence.matchExpressions | nindent 6 }}
{{- end -}}
{{- end }}
{{- if and .Values.enabled .Values.backups.cron.enabled .Values.backups.cron.persistence.enabled }}
{{- if not .Values.backups.cron.persistence.useGenericEphemeralVolume }}
---
kind: PersistentVolumeClaim
apiVersion: v1
{{ include "toolbox.backups.cron.persistence.persistentVolumeClaim" . }}
{{- end -}}
{{- end }}
