annotations:
  artifacthub.io/changes: |
    - "[Added]: Configuration option configs.gpg"
    - "[Deprecated]: Configuration option configs.gpgKeys"
    - "[Deprecated]: Configuration option configs.gpgKeysAnnotations"
    - "[Fixed]: Documentation for declarative setup"
apiVersion: v2
appVersion: v2.5.2
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.22.3
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool
  for Kubernetes.
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- argocd
- gitops
kubeVersion: '>=1.22.0-0'
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-cd
sources:
- https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
- https://github.com/argoproj/argo-cd
version: 5.14.1
