{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "checkout.configMapName" . }}
data:
  {{- if .Values.redis.create }}
  REDIS_URL: redis://checkout-redis:6379
  {{- else }}
  REDIS_URL: redis://{{ .Values.redis.address }}:{{ .Values.redis.port }}
  {{- end }}
  {{- if .Values.endpoints.orders }}
  ENDPOINTS_ORDERS: {{ .Values.endpoints.orders }}
  {{- end }}
{{- end }}
