{{- include "starter-template.validateValues" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starter-template.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "starter-template.labels" . | nindent 4 }}
  {{- with (include "starter-template.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "starter-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "starter-template.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.deployment.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with (include "starter-template.annotations" .) }}
        {{- . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "starter-template.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "starter-template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | nindent 8 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.containerSecurityContext | nindent 12 }}
          image: {{ include "starter-template.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- if or .Values.env .Values.envFrom }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if or .Values.volumeMounts .Values.persistence.enabled }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.persistence.enabled }}
            {{- range .Values.persistence.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- end }}
          {{- end }}
      {{- if or .Values.volumes .Values.persistence.enabled }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        {{- range .Values.persistence.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "starter-template.fullname" $ }}-{{ .name }}
        {{- end }}
        {{- end }}
      {{- end }} 