{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "starter-template.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "starter-template.labels" . | nindent 4 }}
  {{- with (include "starter-template.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }} 