apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: example-grafanadatasource
spec:
  name: middleware.yaml
  datasources:
    - name: Alertmanager
      type: alertmanager
      access: proxy
      url: http://alertmanager-service:9093
      isDefault: true
      version: 1
      editable: true
      jsonData:
        implementation: prometheus # this uses either cortex or prometheus
 
