replicaCount: 1
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: nginx.dive.dev
  path: /
  ingressClassName: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: internal-sg
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: nginx.dive.dev
  tls: false
metrics:
  enabled: true
