# helm diff upgrade nginx-webserver https://github.com/bitnami/charts/tree/main/bitnami/nginx --version 15.1.0 -f ci/my-values.yaml
controller:
  replicaCount: 2
  service:
    type: ClusterIP
  metrics:
    enabled: true
replicaCount: 2
service:
  type: ClusterIP
metrics:
  enabled: true
