{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range $key, $value := .Values.configMap.data }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
