apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: default
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2
        resources:
          # limits:
          #   memory: 512Mi
          requests:
            cpu: 10m
            memory: 10Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - httpd
            topologyKey: kubernetes.io/hostname
            # matchLabelKeys:
            # - pod-template-hash
      tolerations:
      - key: "node"
        value: "service"
        effect: "NoSchedule"
      nodeSelector:
        node: service # 특정 레이블을 가진 노드에 배포
