architecture: replication
auth:
  enabled: false
master:
  count: 1
replica:
  replicaCount: 2
sentinel:
  enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
sysctl:
  enabled: true
