apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-hs
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  ports:
  - port: 2888 
    name: server
  - port: 3888
    name: leader-election
  - port: 7000
    name: metric
  - port: 9100
    name: node-metric
  clusterIP: None
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-cs
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }} 
    name: client
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
