# For use with deploy/examples/datasources/Custom.yaml
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana-with-plugin
spec:
  client:
    preferService: true
  # Plugin requires 8+
  baseImage: docker.io/grafana/grafana:8.4.3
  deployment:
    envFrom:
      - configMapRef:
          name: grafana-plugins
  ingress:
    enabled: True
    pathType: Prefix
    path: "/"
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  service:
    name: "grafana-service"
    labels:
      app: "grafana"
      type: "grafana-service"
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }
  resources:
    # Optionally specify container resources
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-plugins
data:
  GF_INSTALL_PLUGINS: grafadruid-druid-datasource
