controller:
  ingressClassByName: true
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  service:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: $CERT_ARN
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    loadBalancerClass: "service.k8s.aws/nlb"
  metrics:
    enabled: true
  config:
    worker-shutdown-timeout: "21600s"
  terminationGracePeriodSeconds: 21600
