annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added support for ServiceMonitor relabelling."
    - kind: changed
      description: "Updated chart icon path."
    - kind: added
      description: "Added RBAC for Gateway-API resources to ClusterRole."
    - kind: added
      description: "Added RBAC for F5 VirtualServer to ClusterRole."
    - kind: added
      description: "Added support for running ExternalDNS with namespaced scope."
    - kind: changed
      description: "Updated _ExternalDNS_ version to [v0.13.4](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.13.4)."
apiVersion: v2
appVersion: 0.13.4
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with
  DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
keywords:
- kubernetes
- externaldns
- external-dns
- dns
- service
- ingress
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
version: 1.12.2
