authSecret:
  enabled: true
  create: true
  name: "controller-manager"
  github_token: "GITHUB_TOKEN"

image:
  pullPolicy: Always

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 2000

resources:
  limits:
  requests:
    cpu: 100m
    memory: 128Mi

actionsMetricsServer:
  enabled: true
