{{- if .Values.networkpolicy.enabled -}}
{{- $fullName := include "gitlab-zoekt.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab-zoekt.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.networkpolicy.annotations | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gitlab-zoekt.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkpolicy.egress.enabled }}
    - Egress
    {{- end }}
    {{- if .Values.networkpolicy.ingress.enabled }}
    - Ingress
    {{- end }}
  {{- if .Values.networkpolicy.ingress.enabled }}
  ingress:
    {{ toYaml .Values.networkpolicy.ingress.rules | nindent 4 }}
  {{- end -}}
  {{- if .Values.networkpolicy.egress.enabled }}
  egress:
    {{ toYaml .Values.networkpolicy.egress.rules | nindent 4 }}
  {{- end -}}
{{- end -}}
