apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  selector:  # 선택해야 할 파드를 지정
    app: python  # 파드 Label과 동일
  type: ClusterIP
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
