---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: ealen/echo-server:0.9.1
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: echo
        matchLabelKeys:
        - pod-template-hash
      tolerations:
      - key: "node"
        value: "service"
        effect: "NoSchedule"
      nodeSelector:
        node: service # 특정 레이블을 가진 노드에 배포
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - echo
      #       topologyKey: kubernetes.io/hostname
