
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server
  namespace: nfs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 500Gi
