apiVersion: v1
kind: Pod
metadata:
  name: dns-example
spec:
  containers:
  - name: test
    image: nicolaka/netshoot
    command:
    - sleep
    - inf
  dnsConfig:
    options:
      - name: ndots
        value: "2"
