.new-runner-version-changelog: &new-runner-version-changelog
  changelog_entry:
    scope: new-feature
    entry: Update GitLab Runner version to v{{ .Release.AppVersion }}

.update-chart-versions: &update-chart-versions
  write:
    file: Chart.yaml
    contents: |
      apiVersion: v1
      name: gitlab-runner
      version: {{ .Release.Version }}
      appVersion: {{ .Release.AppVersion }}
      description: GitLab Runner
      keywords:
      - git
      - ci
      - deploy
      sources:
      - https://gitlab.com/gitlab-org/charts/gitlab-runner
      - https://gitlab.com/gitlab-org/gitlab-runner
      - https://docs.gitlab.com/runner/
      icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
      maintainers:
      - name: GitLab Inc.
        email: support@gitlab.com

.commit-chart-versions: &commit-chart-versions
  commit:
    files: [Chart.yaml]
    message: Update Chart version to v{{ .Release.Version }} and used GitLab Runner version to v{{ .Release.AppVersion }}

.update-chart-versions-after-merge: &update-chart-versions-after-merge
  write:
    file: Chart.yaml
    contents: |
      apiVersion: v1
      name: gitlab-runner
      version: {{ .Release.VersionObject.NextMinor }}-beta
      appVersion: bleeding
      description: GitLab Runner
      keywords:
      - git
      - ci
      - deploy
      sources:
      - https://gitlab.com/gitlab-org/charts/gitlab-runner
      - https://gitlab.com/gitlab-org/gitlab-runner
      - https://docs.gitlab.com/runner/
      icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
      maintainers:
      - name: GitLab Inc.
        email: support@gitlab.com
    
.commit-chart-versions-after-merge: &commit-chart-versions-after-merge
  commit:
    files: [Chart.yaml]
    message: Update Chart version to v{{ .Release.VersionObject.NextMinor }}-beta and used GitLab Runner version to bleeding
