# permissions for end users to edit grafanafolders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafanafolder-editor-role
rules:
  - apiGroups:
      - integreatly.org
    resources:
      - grafanafolders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
