apiVersion: v2
appVersion: 1.3.1
description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
  cluster.
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
kubeVersion: '>=1.16.0-0'
maintainers:
- email: ritazh@microsoft.com
  name: Rita Zhang
name: secrets-store-csi-driver
sources:
- https://github.com/kubernetes-sigs/secrets-store-csi-driver
version: 1.3.1
