apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-busybox
  namespace: backend
  labels:
    app: backend-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-busybox
  template: 
    metadata:
      labels:
        app: backend-busybox
    spec:
      containers:
      - name: backend-busybox
        image: busybox
        command: ["sh"]
        args: ["-c", "sleep inf"] 
        resources:
          limits:
            # cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - backend-busybox
      #       topologyKey: "kubernetes.io/hostname"
