apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-busybox
  namespace: frontend
  labels:
    app: frontend-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-busybox
  template: 
    metadata:
      labels:
        app: frontend-busybox
    spec:
      containers:
      - name: frontend-busybox
        image: busybox
        command: ["sh"]
        args: ["-c", "sleep inf"] 
        resources:
          limits:
            # cpu: 1000m
            memory: 64Mi
          requests:
            cpu: 500m
            memory: 64Mi
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - frontend-busybox
      #       topologyKey: "kubernetes.io/hostname"
