apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-client
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - name: mongodb
        image: percona/percona-server-mongodb:4.4.24-23
        command: ["tail"]
        args: ["-f", "/dev/null"]
