{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.configMapName" . }}
data:
  SPRING_PROFILES_ACTIVE: mysql,rabbitmq
  SPRING_DATASOURCE_READER_URL: {{ include "orders.mysql.endpoint" . }}
  SPRING_DATASOURCE_WRITER_URL: {{ include "orders.mysql.reader.endpoint" . }}
  SPRING_RABBITMQ_ADDRESSES: {{ include "orders.rabbitmq.addresses" . }}
{{- end }}
