{{- if .Values.mysql.reader.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.reader.secret.name }}
data:
  username: {{ .Values.mysql.reader.secret.username | b64enc | quote }}
  password: "{{ include "orders.mysql.reader.password" . }}"
{{- end }}