# helm install --values values.yaml loki grafana/loki --version 5.36.3 -n monitoring

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::{ACCOUNT_ID}:role/{ROLE_NAME}"

loki:
  storage:
    type: "s3"
    s3:
      region: ap-northeast-2
    bucketNames:
      chunks: {BUCKET_NAME}
      ruler: {BUCKET_NAME}
      admin: {BUCKET_NAME}


# -- Section for configuring optional Helm test
test:
  enabled: false

# Monitoring section determines which monitoring features to enable
monitoring:
  lokiCanary:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
