apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: singapore-test
  securityGroupSelector:
    karpenter.sh/discovery: singapore-test
  tags:
    karpenter.sh/discovery: singapore-test
  blockDeviceMappings: # (2)
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 100Gi
      volumeType: gp3
      encrypted: true
      deleteOnTermination: true
