apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: busybox # POD label과 일치
  template:
    metadata:
      labels:
        app: busybox # Selector label과 일치
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh"]
        args: ["-c", "sleep inf"]
        resources:
          requests:
            cpu: 400m
            memory: 128Mi
