apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx # POD label과 일치
  template:
    metadata:
      labels:
        app: nginx # Selector label과 일치
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 400m
            memory: 128Mi

