apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: webrtc
  namespace: karpenter
spec:
  # References cloud provider-specific custom resource, see your cloud provider specific documentation
  providerRef:
    name: default
  taints:
  - effect: NoSchedule
    key: node
    value: webrtc
  # Labels are arbitrary key-values that are applied to all nodes
  labels:
    nodetype: webrtc
  # Requirements that constrain the parameters of provisioned nodes.
  # These requirements are combined with pod.spec.affinity.nodeAffinity rules.
  # Operators { In, NotIn } are supported to enable including or excluding values
  requirements:
  - key: "karpenter.k8s.aws/instance-family"
    operator: In
    values: ["t3"]
  - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
    operator: In
    values: ["spot"]
  limits:
    resources:
      cpu: "100"
      memory: "200Gi"
  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those
  # that can't be removed.  Mutually exclusive with the ttlSecondsAfterEmpty parameter.
  consolidation:
    enabled: true
