name: Build, Push Docker Image and Update Helm Values

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Install yq
        run: |
          pip install yq

      - name: Checkout helm repository
        uses: actions/checkout@v2
        with:
          repository: tf-dive/kubekube-dive
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: starc-recipes/dev/ns-starc-backend/starc/dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        run: |
          HASH=$(git rev-parse --short HEAD)  # 수정 필요
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:$HASH .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:$HASH
        env:
          GIT_HASH: ${{ github.sha }}

      - name: Update Helm values.yaml
        id: update_helm
        run: |
          HASH=$(git rev-parse --short HEAD) 
          yq eval '.image.tag = strenv(HASH)' -i private-api/ci/values.yaml
        env:
          HASH: ${{ steps.docker_build.outputs.GIT_HASH }}

      - name: Commit and push updated values.yaml
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add private-api/ci/values.yaml
          git commit -m "Update image tag to $HASH"
          git push
        env:
          HASH: ${{ steps.docker_build.outputs.GIT_HASH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
