apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-pdb
  labels:
    app: busybox-pdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-pdb
  template:
    metadata:
      labels:
        app: busybox-pdb
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        name: busybox
      nodeSelector:
        kubernetes.io/hostname: ip-10-110-43-80.ap-northeast-2.compute.internal
