apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Gi
