## values
{{- $fullname := include "kafka.fullname" . }}
{{- $labels := include "kafka.labels" . }}
{{- $selectorLabels := include "kafka.selectorLabels" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-hs
  labels:
    {{- $labels | nindent 4 }}
spec:
  ports:
  {{- range $i, $listener := .Values.configs.listener.listeners }}
    - port: {{ $listener.port }}
      name: client-{{ $i }}
  {{- end }}
  {{  with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  selector:
    {{- $selectorLabels | nindent 4 }}


{{- if eq .Values.service.type "NodePort" }}
  {{- with .Values.service.NodePorts }}
    {{- range $index, $nodeport := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $index }}-cs
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: NodePort
  # sessionAffinity: ClientIP
  ports:
  {{ range $port := $nodeport.ports }}
  - port: {{ $port.port }}
    name: {{ $port.name }}
    {{ with $port.targetPort }}targetPort: {{ . }}{{ end }}
    {{ with $port.nodePort }}nodePort: {{ . }}{{ end }}
  {{- end }}
  selector:
    {{ $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $index }}
##
    {{- end }}
  {{- end }}
{{- end }}