apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:    
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        args:
        - sleep
        - infinity
        volumeMounts:
        - name: date-vol # Volume 이름
          mountPath: /data # Mount 이름
          readOnly: true
      volumes: # 어떤 Volume을 사용할 것인지
      - name: date-vol
        secret:
          secretName: test-tls
