apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - targetPort: {{ .Values.frontend.service.targetPort }}
      port: {{ .Values.frontend.service.port }}
      name: {{ .Values.frontend.service.name }}
  selector:
    app: {{ .Values.frontend.name }}