apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: jerry-test
    Name: "jerry-test-private-ap-northeast-2a"
    # Name: "jerry-test-private-ap-northeast-2*"
  securityGroupSelector:
    karpenter.sh/discovery: jerry-test
  tags:
    karpenter.sh/discovery: jerry-test
  blockDeviceMappings: # (2)
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 100Gi
      volumeType: gp3
      encrypted: true
      deleteOnTermination: true
