apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
spec:
  deployment:
    extraVolumeMounts:
      - mountPath: /data/cache
        name: example-cache
      - mountPath: /opt/extra/secrets
        name: example-secret
    extraVolumes:
      - name: example-cache
        emptyDir: { }
      - name: example-secret
        secret:
          secretName: volume-secret
  ingress:
    enabled: True
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  service:
    name: "grafana-service"
    labels:
      app: "grafana"
      type: "grafana-service"
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [ grafana ] }
  # initResources:
  #   # Optionally specify initResources
  #   limits:
  #     cpu: 1000m
  #     memory: 512Mi
  #   requests:
  #     cpu: 250m
  #     memory: 128Mi
  resources:
    # Optionally specify container resources
    limits:
      cpu: 2000m
      memory: 8000Mi
    requests:
      cpu: 100m
      memory: 200Mi
      