apiVersion: v2
appVersion: 0.27.4
description: A Kubernetes controller that operates self-hosted runners for GitHub
  Actions on your Kubernetes cluster.
home: https://github.com/actions/actions-runner-controller
maintainers:
- name: actions-runner-controller
  url: https://github.com/actions-runner-controller
name: actions-runner-controller
sources:
- https://github.com/actions/actions-runner-controller
type: application
version: 0.23.3
