apiVersion: v1
kind: Secret
metadata:
	name: git-credential
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: junghoon2
  password: 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
