catalog:
  image:
    tag: "10.0"
  
  env:
    - name: AGG_APP_URL
      value: "http://proddetail.workshop:3000/catalogDetail"
    - name: AWS_XRAY_DAEMON_ADDRESS
      value: xray-service.default:2000
    - name: DATABASE_SERVICE_URL
      value: mysql.workshop
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: password
