apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: sgp-demo
  namespace: sgp-demo
spec:
  podSelector: 
    matchLabels:
      app: sgp-demo
  securityGroups:
    groupIds:
      - POD_SG
      - EKS_SG
