---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sgp-demo-index
  namespace: sgp-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to Amazon EKS!</title>
        <style>
            html {color-scheme: light dark;}
            body {width: 35em; margin: 0 auto; font-family: Tahoma, Verdana, Arial, sans-serif;}
        </style>
      </head>
      <body>
        <h1>Welcome to Amazon EKS!</h1>
        <p>If you see this page, you are able successfully access the web application as the network policy allows.</p>
        <p>For online documentation and installation instructions please refer to
          <a href="https://docs.aws.amazon.com/eks/latest/userguide/eks-networking.html">Amazon EKS Networking</a>.<br/><br/>
          The migration guides are available at
          <a href="https://docs.aws.amazon.com/eks/latest/userguide/eks-networking.html">Amazon EKS Network Policy Migration</a>.
        </p>
        <p><em>Thank you for using Amazon EKS.</em></p>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: sgp-demo
  labels:
    app: sgp-demo
  namespace: sgp-demo
spec:
  containers:
  - name: nginx-psql
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: username
    - name: DB_PWD
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: password
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: db-creds
          key: dbhost
    image: sriram430/nginx-psql-client:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-index-volume
  volumes:
  - name: nginx-index-volume
    configMap:
      name: sgp-demo-index
---
apiVersion: v1
kind: Service
metadata:
  name: sgp-demo-svc
  namespace: sgp-demo
  labels:
    app: sgp-demo
spec:
  selector:
    app: sgp-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
