apiVersion: v1
data:
  PostgreSQL_PASSWORD: cGFzc3dvcmQ=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: foo-starter
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-07-25T18:47:36Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: foo-starter-secret
  namespace: default
  resourceVersion: "22418261"
  uid: aa8fcdf5-ab51-4967-8766-44373af69fbf
type: Opaque
