apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secret
  namespace: default
spec:
  encryptedData:
    PostgreSQL_PASSWORD: AgAMmdw96eh/Yu4cXY+aTfXRZDL2tgwVMlqR3cchMp6no3rDoxnp3C2UkQiUBwyhzU+50pAcjO9RldOBofmPyAtRblXwt/qn1WERofP7TmDKrK+82/nAHvHcFUNGcRJfv5A4H0uY4yLrdQt4Gdrc5/Di+USzxl5oxRO7guhtkDr9ejsPdA12NJrIUx9Jd25WSFGqD2nZAw4CCdRbPO1a03v48zixNr82KRrlssjFX7FFAuJD24/xM0uSMV+tBt7w8Vf2G7te6uqRJ0MTZnlg/j712NxrWQnnCWO/yWEh9xZTHinsc3WyrFzt/zB/GQOUieUW3TmaLZDDXaxHc90p88wAbnNj+KWIQo+4MfAneKxmqZuWQ2JR5B700KxFCjHUdVAqupFPb5wB0Q8ogojt2P5M3eQdP+f3TGqupPYi/v+m8c9fVmH3uNKePXs2cm6LYduFCbzwqvhKdA4C63QIwO5zyq7SBajd+yZobVXj7xFcIvTnWiz5RtxTu68CEPODlnOKBlyyAwo8VboFmUYXZ4vUBmzQ/4XDLewysBJJdzqCDpax6TF7BdpiPmDwyxSWbwuVunho1VfRnItEqin3+MkOFmodufWj/pnlAzv1kA1PiYDZVGfYpd9AILYybIwyTdga4MAf29SvjQC+EanjxsywnZQeOd8bbrWpn/+v0sfjEdyxGKNgyyRtMo+izQQDiTH3FjA0yUikNQ==
