apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka01
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - my-values.yaml
    path: kafka
    repoURL: https://github.com/junghoon2/k8s-class.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
