# helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "1.4.0" --namespace "karpenter" --create-namespace -f ci/values.yaml
# helm upgrade karpenter oci://public.ecr.aws/karpenter/karpenter --version "1.4.0" --namespace "karpenter" --create-namespace -f ci/values.yaml

# -- Global Settings to configure Karpenter
settings:
  # -- Cluster name.
  clusterName: "eks-new-vpc-demo"
  interruptionQueue: "karpenter-queue"
  featureGates:
    spotToSpotConsolidation: true

controller:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 1
      memory: 128Mi

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::516696002612:role/KarpenterController-20250430192503981900000001"

serviceMonitor:
  enabled: true
