apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  namespace: default
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: date-vol
      mountPath: /data
  volumes:
  - name: date-vol
    persistentVolumeClaim:
      claimName: ebs-claim
