replicas: 1

controller:
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{aws_account_id}:role/KarpenterIRSA-jerry-test-2023082121002953550000001c

settings:
  aws:
    clusterEndpoint: ${ENDPOINT_ID}
    clusterName: jerry-test
    defaultInstanceProfile: Karpenter-jerry-test-2023082121003044240000001d
    interruptionQueueName: Karpenter-jerry-test
