replicas: 1

controller:
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 800m
      memory: 1Gi

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${ROLE_ARN}

settings:
  aws:
    clusterEndpoint: https://XXXXXXXXXXX.gr7.ap-southeast-1.eks.amazonaws.com
    clusterName: singapore-test
    defaultInstanceProfile: Karpenter-singapore-test-20230522100145161300000009
    interruptionQueueName: Karpenter-singapore-test
